[package]
name = "ai"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.4", features = ["derive"] }
ollama-rs = "0.1"
tokio = { version = "1", features = ["full"] } # Required for async
